"""Offline proof verification for bundles.

This module provides tools to verify bundle integrity without requiring runtime.
"""

from .errors import (
    PROOF_CONTRACT_HASH_INVALID_FORMAT,
    PROOF_CONTRACT_HASH_MISMATCH,
    PROOF_CONTRACT_INVALID_PATH,
    PROOF_CONTRACT_MISSING,
    PROOF_LEDGER_CONTRACT_EXTRA,
    PROOF_LEDGER_CONTRACT_HASH_MISMATCH,
    PROOF_LEDGER_CONTRACT_MISSING,
    PROOF_LEDGER_INVALID_JSON,
    PROOF_LEDGER_INVALID_SCHEMA,
    PROOF_LEDGER_MANIFEST_HASH_INVALID,
    PROOF_LEDGER_MANIFEST_HASH_MISMATCH,
    PROOF_LEDGER_MISSING,
    PROOF_MANIFEST_INVALID_JSON,
    PROOF_MANIFEST_INVALID_SCHEMA,
    PROOF_MANIFEST_MISSING,
    PROOF_PATH_TRAVERSAL,
    PROOF_SOURCE_IDL_INVALID_FORMAT,
    PROOF_SOURCE_IDL_MISSING,
)
from .verify import ProofResult, is_valid_sha256_hex, is_safe_path, verify_bundle_offline

__all__ = [
    # Main API
    "verify_bundle_offline",
    "ProofResult",
    "is_valid_sha256_hex",
    "is_safe_path",
    # Error codes
    "PROOF_MANIFEST_MISSING",
    "PROOF_MANIFEST_INVALID_JSON",
    "PROOF_MANIFEST_INVALID_SCHEMA",
    "PROOF_CONTRACT_MISSING",
    "PROOF_CONTRACT_HASH_MISMATCH",
    "PROOF_CONTRACT_INVALID_PATH",
    "PROOF_CONTRACT_HASH_INVALID_FORMAT",
    "PROOF_LEDGER_MISSING",
    "PROOF_LEDGER_INVALID_JSON",
    "PROOF_LEDGER_INVALID_SCHEMA",
    "PROOF_LEDGER_MANIFEST_HASH_MISMATCH",
    "PROOF_LEDGER_MANIFEST_HASH_INVALID",
    "PROOF_LEDGER_CONTRACT_MISSING",
    "PROOF_LEDGER_CONTRACT_EXTRA",
    "PROOF_LEDGER_CONTRACT_HASH_MISMATCH",
    "PROOF_SOURCE_IDL_MISSING",
    "PROOF_SOURCE_IDL_INVALID_FORMAT",
    "PROOF_PATH_TRAVERSAL",
]
