"""Error codes for offline proof verification.

All error codes are deterministic and stable for CI/audit use.
"""

# Manifest errors
PROOF_MANIFEST_MISSING = "PROOF_MANIFEST_MISSING"
PROOF_MANIFEST_INVALID_JSON = "PROOF_MANIFEST_INVALID_JSON"
PROOF_MANIFEST_INVALID_SCHEMA = "PROOF_MANIFEST_INVALID_SCHEMA"

# Contract errors
PROOF_CONTRACT_MISSING = "PROOF_CONTRACT_MISSING"
PROOF_CONTRACT_HASH_MISMATCH = "PROOF_CONTRACT_HASH_MISMATCH"
PROOF_CONTRACT_INVALID_PATH = "PROOF_CONTRACT_INVALID_PATH"
PROOF_CONTRACT_HASH_INVALID_FORMAT = "PROOF_CONTRACT_HASH_INVALID_FORMAT"

# Ledger errors
PROOF_LEDGER_MISSING = "PROOF_LEDGER_MISSING"
PROOF_LEDGER_INVALID_JSON = "PROOF_LEDGER_INVALID_JSON"
PROOF_LEDGER_INVALID_SCHEMA = "PROOF_LEDGER_INVALID_SCHEMA"
PROOF_LEDGER_MANIFEST_HASH_MISMATCH = "PROOF_LEDGER_MANIFEST_HASH_MISMATCH"
PROOF_LEDGER_MANIFEST_HASH_INVALID = "PROOF_LEDGER_MANIFEST_HASH_INVALID"
PROOF_LEDGER_CONTRACT_MISSING = "PROOF_LEDGER_CONTRACT_MISSING"
PROOF_LEDGER_CONTRACT_EXTRA = "PROOF_LEDGER_CONTRACT_EXTRA"
PROOF_LEDGER_CONTRACT_HASH_MISMATCH = "PROOF_LEDGER_CONTRACT_HASH_MISMATCH"

# Source IDL errors
PROOF_SOURCE_IDL_MISSING = "PROOF_SOURCE_IDL_MISSING"
PROOF_SOURCE_IDL_INVALID_FORMAT = "PROOF_SOURCE_IDL_INVALID_FORMAT"

# Path traversal errors
PROOF_PATH_TRAVERSAL = "PROOF_PATH_TRAVERSAL"
