"""ISE Error codes."""

# Parse errors
ISE_IDL_PARSE_FAILED = "ISE_IDL_PARSE_FAILED"
ISE_IDL_INVALID_JSON = "ISE_IDL_INVALID_JSON"
ISE_IDL_MISSING_FIELD = "ISE_IDL_MISSING_FIELD"

# Validation errors
ISE_IDL_INSUFFICIENT = "ISE_IDL_INSUFFICIENT"
ISE_APPROVAL_UNMAPPED = "ISE_APPROVAL_UNMAPPED"
ISE_SOD_UNMAPPED = "ISE_SOD_UNMAPPED"
ISE_ENTITY_MISSING = "ISE_ENTITY_MISSING"

# Compilation errors
ISE_COMPILE_FAILED = "ISE_COMPILE_FAILED"
ISE_EMIT_FAILED = "ISE_EMIT_FAILED"
ISE_MANIFEST_FAILED = "ISE_MANIFEST_FAILED"

# Bundle errors
ISE_BUNDLE_EXISTS = "ISE_BUNDLE_EXISTS"
ISE_BUNDLE_WRITE_FAILED = "ISE_BUNDLE_WRITE_FAILED"

# Release errors
ISE_ADMIN_UNAUTHORIZED = "ISE_ADMIN_UNAUTHORIZED"
ISE_SCRIPT_UNAVAILABLE = "ISE_SCRIPT_UNAVAILABLE"
ISE_RELEASE_WRITE_FAILED = "ISE_RELEASE_WRITE_FAILED"
ISE_VERIFY_FAILED = "ISE_VERIFY_FAILED"
ISE_DEPLOY_FAILED = "ISE_DEPLOY_FAILED"

# Multi-department errors
ISE_DEPT_ID_INVALID = "ISE_DEPT_ID_INVALID"
ISE_CONTRACT_PROVIDER_UNKNOWN = "ISE_CONTRACT_PROVIDER_UNKNOWN"
ISE_CONTRACT_CONSUMER_UNKNOWN = "ISE_CONTRACT_CONSUMER_UNKNOWN"
ISE_CONTRACT_ID_INVALID = "ISE_CONTRACT_ID_INVALID"

# Policy errors
ISE_POLICY_INVALID = "ISE_POLICY_INVALID"

# Mandate errors (IDL v1.1)
ISE_MANDATE_INVALID = "ISE_MANDATE_INVALID"
ISE_MANDATE_ENDPOINT_INVALID = "ISE_MANDATE_ENDPOINT_INVALID"
ISE_MANDATE_PHASE_INVALID = "ISE_MANDATE_PHASE_INVALID"
ISE_MANDATE_RULE_TYPE_INVALID = "ISE_MANDATE_RULE_TYPE_INVALID"
ISE_MANDATE_ID_DUPLICATE = "ISE_MANDATE_ID_DUPLICATE"

# Autonomy errors (IDL v1.1)
ISE_AUTONOMY_INVALID = "ISE_AUTONOMY_INVALID"
ISE_AUTONOMY_LEVEL_INVALID = "ISE_AUTONOMY_LEVEL_INVALID"
ISE_AUTONOMY_ENDPOINT_INVALID = "ISE_AUTONOMY_ENDPOINT_INVALID"
ISE_AUTONOMY_PHASE_INVALID = "ISE_AUTONOMY_PHASE_INVALID"
ISE_AUTONOMY_RULE_ID_DUPLICATE = "ISE_AUTONOMY_RULE_ID_DUPLICATE"
