"""Tests for ISE → Loader compatibility.

Validates that bundles generated by the ISE compiler can be loaded by the runtime loader.
Per MVP decision (2026-01-17): policies.json, mandates.json, autonomy.json are mandatory.
"""

import json
import os
import tempfile
import pytest
from pathlib import Path

from engine.ise.compiler import compile_bundle
from engine.ise.manifest import REQUIRED_CONTRACTS
from engine.loader.load_bundle import load_bundle
from engine.loader.verify_hashes import verify_contract_hash, normalize_hash
from engine.core.runtime_state import runtime_state


# Minimal valid IDL for finance-pilot MVP
MINIMAL_IDL = json.dumps({
    "idl_version": "1.0",
    "system_name": "Test System",
    "version": "1.0.0",
    "actors": [
        {
            "name": "Employee",
            "permissions": [
                {"resource": "expense", "actions": ["create"]}
            ]
        },
        {
            "name": "Manager",
            "permissions": [
                {"resource": "expense", "actions": ["read", "approve"]}
            ]
        }
    ],
    "entities": [
        {
            "name": "expense",
            "fields": [
                {"name": "amount", "type": "decimal"},
                {"name": "description", "type": "string"}
            ]
        }
    ],
    "usecases": [
        {
            "name": "create_expense",
            "actor": "Employee",
            "steps": ["Submit expense for approval"]
        }
    ]
})


class TestISELoaderCompatibility:
    """Test that ISE-generated bundles load in the runtime loader."""

    def setup_method(self):
        """Clear safe mode before each test."""
        runtime_state.set_active()

    def teardown_method(self):
        """Clear safe mode after each test."""
        runtime_state.set_active()

    def test_ise_bundle_manifest_format(self):
        """Test that ISE generates manifest in loader-compatible format."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success, f"Compilation failed: {result.error_message}"

            # Read the generated manifest
            manifest_path = Path(tmpdir) / "test-bundle" / "bundle.manifest.json"
            assert manifest_path.exists()

            with open(manifest_path) as f:
                manifest = json.load(f)

            # Verify loader-compatible format
            assert "name" in manifest, "Manifest should have 'name' field"
            assert "version" in manifest, "Manifest should have 'version' field"
            assert "contracts" in manifest, "Manifest should have 'contracts' field"
            assert isinstance(manifest["contracts"], list), "contracts should be a list"

            # Verify contract entries have required fields
            for contract in manifest["contracts"]:
                assert "file" in contract, "Contract should have 'file' field"
                assert "sha256" in contract, "Contract should have 'sha256' field"
                assert "required" in contract, "Contract should have 'required' field"

    def test_ise_bundle_emits_institutional_contracts(self):
        """Test that ISE emits all mandatory institutional contracts."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success, f"Compilation failed: {result.error_message}"

            bundle_path = Path(tmpdir) / "test-bundle"

            # Verify all mandatory contracts exist
            assert (bundle_path / "policies.json").exists(), "policies.json should exist"
            assert (bundle_path / "mandates.json").exists(), "mandates.json should exist"
            assert (bundle_path / "autonomy.json").exists(), "autonomy.json should exist"

            # Verify they are valid JSON
            for filename in ["policies.json", "mandates.json", "autonomy.json"]:
                with open(bundle_path / filename) as f:
                    data = json.load(f)
                    assert isinstance(data, dict), f"{filename} should be valid JSON dict"

    def test_ise_bundle_contracts_marked_required(self):
        """Test that institutional contracts are marked as required in manifest."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success

            manifest_path = Path(tmpdir) / "test-bundle" / "bundle.manifest.json"
            with open(manifest_path) as f:
                manifest = json.load(f)

            # Find institutional contracts in manifest
            institutional = {"policies.json", "mandates.json", "autonomy.json"}
            for contract in manifest["contracts"]:
                if contract["file"] in institutional:
                    assert contract["required"] is True, \
                        f"{contract['file']} should be marked as required"

    def test_ise_bundle_hash_format(self):
        """Test that ISE generates hashes in SHA256: prefix format."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success

            manifest_path = Path(tmpdir) / "test-bundle" / "bundle.manifest.json"
            with open(manifest_path) as f:
                manifest = json.load(f)

            for contract in manifest["contracts"]:
                sha256 = contract["sha256"]
                assert sha256.startswith("SHA256:"), \
                    f"Hash should start with SHA256: prefix, got: {sha256}"
                # Verify it's valid hex after prefix
                hex_part = sha256[7:]
                assert len(hex_part) == 64, f"Hash should be 64 hex chars, got {len(hex_part)}"
                assert all(c in "0123456789abcdef" for c in hex_part), \
                    f"Hash should be hex, got: {hex_part}"

    def test_ise_bundle_hash_verification(self):
        """Test that ISE-generated hashes match actual file contents."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success

            bundle_path = Path(tmpdir) / "test-bundle"
            manifest_path = bundle_path / "bundle.manifest.json"
            with open(manifest_path) as f:
                manifest = json.load(f)

            for contract in manifest["contracts"]:
                if contract["file"] == "bundle.manifest.json":
                    continue  # Skip manifest itself

                file_path = bundle_path / contract["file"]
                if file_path.exists():
                    assert verify_contract_hash(file_path, contract["sha256"]), \
                        f"Hash mismatch for {contract['file']}"

    def test_ise_bundle_loads_in_loader(self):
        """Test that ISE-generated bundle loads successfully in runtime loader."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success, f"Compilation failed: {result.error_message}"

            bundle_path = Path(tmpdir) / "test-bundle"

            # Set environment to use our bundle
            os.environ["ENGINE_BUNDLE_PATH"] = str(bundle_path)

            try:
                # Load the bundle
                load_bundle()

                # Should NOT be in safe mode
                assert not runtime_state.is_safe_mode(), \
                    f"Loader entered SAFE_MODE: {runtime_state.reason_code} - {runtime_state.details}"
            finally:
                os.environ.pop("ENGINE_BUNDLE_PATH", None)

    def test_ise_bundle_all_required_contracts_present(self):
        """Test that all required contracts from REQUIRED_CONTRACTS are emitted."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success

            bundle_path = Path(tmpdir) / "test-bundle"

            # Check all required contracts exist
            for contract_name in REQUIRED_CONTRACTS:
                assert (bundle_path / contract_name).exists(), \
                    f"Required contract {contract_name} should exist"


class TestISEMandatesEmit:
    """Test mandates.json emission."""

    def test_mandates_schema_version(self):
        """Test that mandates.json has correct schema version."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success

            mandates_path = Path(tmpdir) / "test-bundle" / "mandates.json"
            with open(mandates_path) as f:
                mandates = json.load(f)

            assert mandates["mandate_schema_version"] == "1.0"
            assert "mandates" in mandates
            assert isinstance(mandates["mandates"], list)


class TestISEAutonomyEmit:
    """Test autonomy.json emission."""

    def test_autonomy_schema_version(self):
        """Test that autonomy.json has correct schema version."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success

            autonomy_path = Path(tmpdir) / "test-bundle" / "autonomy.json"
            with open(autonomy_path) as f:
                autonomy = json.load(f)

            assert autonomy["autonomy_schema_version"] == "1.0"
            assert "current_level" in autonomy
            assert "rules" in autonomy
            assert isinstance(autonomy["rules"], list)

    def test_autonomy_default_level_is_restrictive(self):
        """Test that default autonomy level is L0 (most restrictive)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = compile_bundle(
                idl=MINIMAL_IDL,
                bundle_name="test-bundle",
                output_dir=tmpdir,
                validate_finance_pilot=True,
            )

            assert result.success

            autonomy_path = Path(tmpdir) / "test-bundle" / "autonomy.json"
            with open(autonomy_path) as f:
                autonomy = json.load(f)

            # Default should be L0 (full human oversight)
            assert autonomy["current_level"] == 0, \
                "Default autonomy level should be 0 (L0 - full human oversight)"


class TestHashNormalization:
    """Test hash normalization for loader compatibility."""

    def test_normalize_hash_with_prefix(self):
        """Test that SHA256: prefix is properly stripped."""
        hash_with_prefix = "SHA256:a1b2c3d4e5f6"
        normalized = normalize_hash(hash_with_prefix)
        assert normalized == "a1b2c3d4e5f6"

    def test_normalize_hash_without_prefix(self):
        """Test that hash without prefix is returned as-is."""
        hash_without_prefix = "a1b2c3d4e5f6"
        normalized = normalize_hash(hash_without_prefix)
        assert normalized == "a1b2c3d4e5f6"

    def test_normalize_hash_lowercase(self):
        """Test that hash is lowercased."""
        hash_upper = "SHA256:A1B2C3D4E5F6"
        normalized = normalize_hash(hash_upper)
        assert normalized == "a1b2c3d4e5f6"
