"""NL Pipeline Error Codes."""

# SIR extraction errors
NL_EMPTY_INPUT = "NL_EMPTY_INPUT"
NL_EXTRACTION_FAILED = "NL_EXTRACTION_FAILED"
NL_INVALID_LANGUAGE = "NL_INVALID_LANGUAGE"

# Draft generation errors
NL_DRAFT_FAILED = "NL_DRAFT_FAILED"
NL_SIR_INVALID = "NL_SIR_INVALID"
NL_NO_POLICIES = "NL_NO_POLICIES"

# Gap detection errors
NL_GAP_DETECTION_FAILED = "NL_GAP_DETECTION_FAILED"

# Answer apply errors
NL_ANSWERS_INVALID = "NL_ANSWERS_INVALID"
NL_ANSWER_MISMATCH = "NL_ANSWER_MISMATCH"
NL_QUESTION_NOT_FOUND = "NL_QUESTION_NOT_FOUND"

# Finalize errors
NL_FINALIZE_FAILED = "NL_FINALIZE_FAILED"
NL_GAPS_REMAINING = "NL_GAPS_REMAINING"
NL_VALIDATION_FAILED = "NL_VALIDATION_FAILED"
NL_POLICY_INVALID = "NL_POLICY_INVALID"

# Schema errors
NL_SCHEMA_VERSION_UNSUPPORTED = "NL_SCHEMA_VERSION_UNSUPPORTED"
