"""Core module - runtime state, errors, actor context, RBAC, ledger, and approvals."""

from .runtime_state import runtime_state, RuntimeState, RuntimeMode
from .errors import (
    BUNDLE_MANIFEST_MISSING,
    BUNDLE_MANIFEST_INVALID_JSON,
    BUNDLE_CONTRACT_MISSING,
    BUNDLE_CONTRACT_HASH_MISMATCH,
    BUNDLE_CONTRACT_INVALID_JSON,
    BUNDLE_LEDGER_INVALID,
    BUNDLE_UNKNOWN_ERROR,
)
from .actor_context import ActorContext, parse_actor_context, is_valid_uuid, DEFAULT_TENANT_ID
from .rbac import RBACPolicy, gate_rbac, set_rbac_policy, get_rbac_policy
from .ledger import (
    AuditLedger,
    LedgerEvent,
    HistoryResult,
    get_ledger,
    set_ledger,
    init_ledger,
    GENESIS_HASH,
)
from .approvals import (
    ApprovalRule,
    ApprovalsPolicy,
    get_approvals_policy,
    set_approvals_policy,
    compute_payload_sha256,
    generate_approval_id,
    get_approval_step_name,
    emit_approval_requested,
    emit_approval_decided,
    find_approval_requested,
    find_approval_decided,
    is_approval_decided,
    can_actor_decide,
    get_rule_name_from_step,
)

__all__ = [
    "runtime_state",
    "RuntimeState",
    "RuntimeMode",
    "BUNDLE_MANIFEST_MISSING",
    "BUNDLE_MANIFEST_INVALID_JSON",
    "BUNDLE_CONTRACT_MISSING",
    "BUNDLE_CONTRACT_HASH_MISMATCH",
    "BUNDLE_CONTRACT_INVALID_JSON",
    "BUNDLE_LEDGER_INVALID",
    "BUNDLE_UNKNOWN_ERROR",
    "ActorContext",
    "parse_actor_context",
    "is_valid_uuid",
    "DEFAULT_TENANT_ID",
    "RBACPolicy",
    "gate_rbac",
    "set_rbac_policy",
    "get_rbac_policy",
    "AuditLedger",
    "LedgerEvent",
    "HistoryResult",
    "get_ledger",
    "set_ledger",
    "init_ledger",
    "GENESIS_HASH",
    "ApprovalRule",
    "ApprovalsPolicy",
    "get_approvals_policy",
    "set_approvals_policy",
    "compute_payload_sha256",
    "generate_approval_id",
    "get_approval_step_name",
    "emit_approval_requested",
    "emit_approval_decided",
    "find_approval_requested",
    "find_approval_decided",
    "is_approval_decided",
    "can_actor_decide",
    "get_rule_name_from_step",
]
