"""Reason codes for Safe Mode."""

# Bundle manifest errors
BUNDLE_MANIFEST_MISSING = "BUNDLE_MANIFEST_MISSING"
BUNDLE_MANIFEST_INVALID_JSON = "BUNDLE_MANIFEST_INVALID_JSON"

# Contract errors
BUNDLE_CONTRACT_MISSING = "BUNDLE_CONTRACT_MISSING"
BUNDLE_CONTRACT_HASH_MISMATCH = "BUNDLE_CONTRACT_HASH_MISMATCH"
BUNDLE_CONTRACT_INVALID_JSON = "BUNDLE_CONTRACT_INVALID_JSON"

# Ledger errors
BUNDLE_LEDGER_INVALID = "BUNDLE_LEDGER_INVALID"
LEDGER_TAMPER_DETECTED = "LEDGER_TAMPER_DETECTED"
LEDGER_VERIFY_UNAVAILABLE = "LEDGER_VERIFY_UNAVAILABLE"

# Generic error
BUNDLE_UNKNOWN_ERROR = "BUNDLE_UNKNOWN_ERROR"

# SoD errors
SOD_VIOLATION = "SOD_VIOLATION"
SOD_RULE_INVALID = "SOD_RULE_INVALID"

# Case errors
CASE_NOT_FOUND = "CASE_NOT_FOUND"

# Invariant errors
INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
INVARIANT_SCHEMA_INVALID = "INVARIANT_SCHEMA_INVALID"

# State store errors
STATE_STORE_UNAVAILABLE = "STATE_STORE_UNAVAILABLE"
STATE_STORE_DEPT_INVALID = "STATE_STORE_DEPT_INVALID"

# Multi-department bundle errors
BUNDLE_MULTI_DEPT_MISSING_CONTRACTS = "BUNDLE_MULTI_DEPT_MISSING_CONTRACTS"
BUNDLE_DEPT_ARTIFACT_MISSING = "BUNDLE_DEPT_ARTIFACT_MISSING"
BUNDLE_DEPT_ARTIFACT_INVALID = "BUNDLE_DEPT_ARTIFACT_INVALID"

# Department routing errors
DEPT_UNKNOWN = "DEPT_UNKNOWN"
DEPT_MODE_REQUIRED = "DEPT_MODE_REQUIRED"

# Interdepartmental contract errors
CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
CONTRACT_PROVIDER_MISMATCH = "CONTRACT_PROVIDER_MISMATCH"
CONTRACT_CONSUMER_FORBIDDEN = "CONTRACT_CONSUMER_FORBIDDEN"
CONTRACT_CASE_ID_REQUIRED = "CONTRACT_CASE_ID_REQUIRED"
CONTRACT_DECISION_INVALID = "CONTRACT_DECISION_INVALID"

# Policy errors
POLICY_DENIED = "POLICY_DENIED"
POLICY_INVALID = "POLICY_INVALID"
POLICY_ENGINE_UNAVAILABLE = "POLICY_ENGINE_UNAVAILABLE"
POLICY_ENDPOINT_UNKNOWN = "POLICY_ENDPOINT_UNKNOWN"
POLICY_PATH_INVALID = "POLICY_PATH_INVALID"

# Mandate errors
MANDATE_INVALID = "MANDATE_INVALID"
MANDATE_DENIED = "MANDATE_DENIED"
MANDATE_EXPIRED = "MANDATE_EXPIRED"
MANDATE_ROLE_MISMATCH = "MANDATE_ROLE_MISMATCH"

# Autonomy errors
AUTONOMY_INVALID = "AUTONOMY_INVALID"
AUTONOMY_INSUFFICIENT = "AUTONOMY_INSUFFICIENT"
AUTONOMY_ENDPOINT_UNKNOWN = "AUTONOMY_ENDPOINT_UNKNOWN"
AUTONOMY_LEVEL_INVALID = "AUTONOMY_LEVEL_INVALID"

# Institution errors
INSTITUTION_SLUG_INVALID = "INSTITUTION_SLUG_INVALID"
INSTITUTION_SLUG_TAKEN = "INSTITUTION_SLUG_TAKEN"
INSTITUTION_NOT_FOUND = "INSTITUTION_NOT_FOUND"
INSTITUTION_ID_INVALID = "INSTITUTION_ID_INVALID"
INSTITUTIONS_REGISTRY_UNAVAILABLE = "INSTITUTIONS_REGISTRY_UNAVAILABLE"
INSTITUTION_META_UNAVAILABLE = "INSTITUTION_META_UNAVAILABLE"

# Institution context errors
INSTITUTION_HEADER_REQUIRED = "INSTITUTION_HEADER_REQUIRED"
INSTITUTION_HEADER_CONFLICT = "INSTITUTION_HEADER_CONFLICT"
INSTITUTION_HEADER_INVALID = "INSTITUTION_HEADER_INVALID"
INSTITUTION_CONTEXT_UNAVAILABLE = "INSTITUTION_CONTEXT_UNAVAILABLE"

# Institution config errors
INSTITUTION_CONFIG_INVALID = "INSTITUTION_CONFIG_INVALID"
INSTITUTION_CONFIG_UNAVAILABLE = "INSTITUTION_CONFIG_UNAVAILABLE"
INSTITUTION_CONFIG_HISTORY_UNAVAILABLE = "INSTITUTION_CONFIG_HISTORY_UNAVAILABLE"

# Institution freeze/emergency stop errors
INSTITUTION_FROZEN = "INSTITUTION_FROZEN"
INSTITUTION_EMERGENCY_STOPPED = "INSTITUTION_EMERGENCY_STOPPED"
INSTITUTION_EMERGENCY_ENDPOINT_UNKNOWN = "INSTITUTION_EMERGENCY_ENDPOINT_UNKNOWN"

# Admin key errors
ADMIN_KEY_REQUIRED = "ADMIN_KEY_REQUIRED"
ADMIN_KEY_INVALID = "ADMIN_KEY_INVALID"
ADMIN_KEY_REVOKED = "ADMIN_KEY_REVOKED"
ADMIN_KEY_EXPIRED = "ADMIN_KEY_EXPIRED"
ADMIN_KEY_NOT_FOUND = "ADMIN_KEY_NOT_FOUND"
ADMIN_KEY_ALREADY_REVOKED = "ADMIN_KEY_ALREADY_REVOKED"
ADMIN_KEYS_REGISTRY_UNAVAILABLE = "ADMIN_KEYS_REGISTRY_UNAVAILABLE"

# EGE (Engine Governance Enforcement) errors
EGE_STATE_UNAVAILABLE = "EGE_STATE_UNAVAILABLE"
EGE_REGISTRY_UNAVAILABLE = "EGE_REGISTRY_UNAVAILABLE"
EGE_DRIFT_BLOCKED = "EGE_DRIFT_BLOCKED"
EGE_NO_DRIFT_ACTIVE = "EGE_NO_DRIFT_ACTIVE"
EGE_PROPOSAL_NOT_FOUND = "EGE_PROPOSAL_NOT_FOUND"
EGE_PROPOSAL_ALREADY_DECIDED = "EGE_PROPOSAL_ALREADY_DECIDED"
EGE_DECISION_INVALID = "EGE_DECISION_INVALID"

# EGE Pin errors (8.1.1)
EGE_PIN_PROPOSAL_NOT_FOUND = "EGE_PIN_PROPOSAL_NOT_FOUND"
EGE_PIN_PROPOSAL_WRONG_TYPE = "EGE_PIN_PROPOSAL_WRONG_TYPE"
EGE_PIN_ALREADY_MATCHED = "EGE_PIN_ALREADY_MATCHED"
EGE_PIN_CONFIG_UNAVAILABLE = "EGE_PIN_CONFIG_UNAVAILABLE"
EGE_PIN_OBSERVED_UNAVAILABLE = "EGE_PIN_OBSERVED_UNAVAILABLE"
