"""Reason codes for Safe Mode."""

# Bundle manifest errors
BUNDLE_MANIFEST_MISSING = "BUNDLE_MANIFEST_MISSING"
BUNDLE_MANIFEST_INVALID_JSON = "BUNDLE_MANIFEST_INVALID_JSON"

# Contract errors
BUNDLE_CONTRACT_MISSING = "BUNDLE_CONTRACT_MISSING"
BUNDLE_CONTRACT_HASH_MISMATCH = "BUNDLE_CONTRACT_HASH_MISMATCH"
BUNDLE_CONTRACT_INVALID_JSON = "BUNDLE_CONTRACT_INVALID_JSON"

# Ledger errors
BUNDLE_LEDGER_INVALID = "BUNDLE_LEDGER_INVALID"
LEDGER_TAMPER_DETECTED = "LEDGER_TAMPER_DETECTED"
LEDGER_VERIFY_UNAVAILABLE = "LEDGER_VERIFY_UNAVAILABLE"

# Generic error
BUNDLE_UNKNOWN_ERROR = "BUNDLE_UNKNOWN_ERROR"

# SoD errors
SOD_VIOLATION = "SOD_VIOLATION"
SOD_RULE_INVALID = "SOD_RULE_INVALID"

# Case errors
CASE_NOT_FOUND = "CASE_NOT_FOUND"
EXPENSE_NOT_FOUND = "EXPENSE_NOT_FOUND"
TICKET_NOT_FOUND = "TICKET_NOT_FOUND"

# Bazari MVP entity errors
CONTENT_REPORT_NOT_FOUND = "CONTENT_REPORT_NOT_FOUND"
CHAT_REPORT_NOT_FOUND = "CHAT_REPORT_NOT_FOUND"
CHAT_BLOCK_NOT_FOUND = "CHAT_BLOCK_NOT_FOUND"
MODERATION_ACTION_NOT_FOUND = "MODERATION_ACTION_NOT_FOUND"

# Invariant errors
INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
INVARIANT_SCHEMA_INVALID = "INVARIANT_SCHEMA_INVALID"

# State store errors
STATE_STORE_UNAVAILABLE = "STATE_STORE_UNAVAILABLE"
STATE_STORE_DEPT_INVALID = "STATE_STORE_DEPT_INVALID"

# Multi-department bundle errors
BUNDLE_MULTI_DEPT_MISSING_CONTRACTS = "BUNDLE_MULTI_DEPT_MISSING_CONTRACTS"
BUNDLE_DEPT_ARTIFACT_MISSING = "BUNDLE_DEPT_ARTIFACT_MISSING"
BUNDLE_DEPT_ARTIFACT_INVALID = "BUNDLE_DEPT_ARTIFACT_INVALID"

# Department routing errors
DEPT_UNKNOWN = "DEPT_UNKNOWN"
DEPT_MODE_REQUIRED = "DEPT_MODE_REQUIRED"

# Interdepartmental contract errors
CONTRACT_NOT_FOUND = "CONTRACT_NOT_FOUND"
CONTRACT_PROVIDER_MISMATCH = "CONTRACT_PROVIDER_MISMATCH"
CONTRACT_CONSUMER_FORBIDDEN = "CONTRACT_CONSUMER_FORBIDDEN"
CONTRACT_CASE_ID_REQUIRED = "CONTRACT_CASE_ID_REQUIRED"
CONTRACT_DECISION_INVALID = "CONTRACT_DECISION_INVALID"

# Policy errors
POLICY_DENIED = "POLICY_DENIED"
POLICY_INVALID = "POLICY_INVALID"
POLICY_ENGINE_UNAVAILABLE = "POLICY_ENGINE_UNAVAILABLE"
POLICY_ENDPOINT_UNKNOWN = "POLICY_ENDPOINT_UNKNOWN"
POLICY_PATH_INVALID = "POLICY_PATH_INVALID"

# Mandate errors
MANDATE_INVALID = "MANDATE_INVALID"
MANDATE_DENIED = "MANDATE_DENIED"
MANDATE_EXPIRED = "MANDATE_EXPIRED"
MANDATE_ROLE_MISMATCH = "MANDATE_ROLE_MISMATCH"

# Autonomy errors
AUTONOMY_INVALID = "AUTONOMY_INVALID"
AUTONOMY_INSUFFICIENT = "AUTONOMY_INSUFFICIENT"
AUTONOMY_ENDPOINT_UNKNOWN = "AUTONOMY_ENDPOINT_UNKNOWN"
AUTONOMY_LEVEL_INVALID = "AUTONOMY_LEVEL_INVALID"

# Institution errors
INSTITUTION_SLUG_INVALID = "INSTITUTION_SLUG_INVALID"
INSTITUTION_SLUG_TAKEN = "INSTITUTION_SLUG_TAKEN"
INSTITUTION_NOT_FOUND = "INSTITUTION_NOT_FOUND"
INSTITUTION_ID_INVALID = "INSTITUTION_ID_INVALID"
INSTITUTIONS_REGISTRY_UNAVAILABLE = "INSTITUTIONS_REGISTRY_UNAVAILABLE"
INSTITUTION_META_UNAVAILABLE = "INSTITUTION_META_UNAVAILABLE"

# Institution context errors
INSTITUTION_HEADER_REQUIRED = "INSTITUTION_HEADER_REQUIRED"
INSTITUTION_HEADER_CONFLICT = "INSTITUTION_HEADER_CONFLICT"
INSTITUTION_HEADER_INVALID = "INSTITUTION_HEADER_INVALID"
INSTITUTION_CONTEXT_UNAVAILABLE = "INSTITUTION_CONTEXT_UNAVAILABLE"

# Institution config errors
INSTITUTION_CONFIG_INVALID = "INSTITUTION_CONFIG_INVALID"
INSTITUTION_CONFIG_UNAVAILABLE = "INSTITUTION_CONFIG_UNAVAILABLE"
INSTITUTION_CONFIG_HISTORY_UNAVAILABLE = "INSTITUTION_CONFIG_HISTORY_UNAVAILABLE"

# Institution freeze/emergency stop errors
INSTITUTION_FROZEN = "INSTITUTION_FROZEN"
INSTITUTION_EMERGENCY_STOPPED = "INSTITUTION_EMERGENCY_STOPPED"
INSTITUTION_EMERGENCY_ENDPOINT_UNKNOWN = "INSTITUTION_EMERGENCY_ENDPOINT_UNKNOWN"

# Admin key errors
ADMIN_KEY_REQUIRED = "ADMIN_KEY_REQUIRED"
ADMIN_KEY_INVALID = "ADMIN_KEY_INVALID"
ADMIN_KEY_REVOKED = "ADMIN_KEY_REVOKED"
ADMIN_KEY_EXPIRED = "ADMIN_KEY_EXPIRED"
ADMIN_KEY_NOT_FOUND = "ADMIN_KEY_NOT_FOUND"
ADMIN_KEY_ALREADY_REVOKED = "ADMIN_KEY_ALREADY_REVOKED"
ADMIN_KEY_BOOTSTRAP_NOT_ALLOWED = "ADMIN_KEY_BOOTSTRAP_NOT_ALLOWED"
ADMIN_KEYS_REGISTRY_UNAVAILABLE = "ADMIN_KEYS_REGISTRY_UNAVAILABLE"

# EGE (Engine Governance Enforcement) errors
EGE_STATE_UNAVAILABLE = "EGE_STATE_UNAVAILABLE"
EGE_REGISTRY_UNAVAILABLE = "EGE_REGISTRY_UNAVAILABLE"
EGE_DRIFT_BLOCKED = "EGE_DRIFT_BLOCKED"
EGE_NO_DRIFT_ACTIVE = "EGE_NO_DRIFT_ACTIVE"
EGE_PROPOSAL_NOT_FOUND = "EGE_PROPOSAL_NOT_FOUND"
EGE_PROPOSAL_ALREADY_DECIDED = "EGE_PROPOSAL_ALREADY_DECIDED"
EGE_DECISION_INVALID = "EGE_DECISION_INVALID"

# EGE Pin errors (8.1.1)
EGE_PIN_PROPOSAL_NOT_FOUND = "EGE_PIN_PROPOSAL_NOT_FOUND"
EGE_PIN_PROPOSAL_WRONG_TYPE = "EGE_PIN_PROPOSAL_WRONG_TYPE"
EGE_PIN_ALREADY_MATCHED = "EGE_PIN_ALREADY_MATCHED"
EGE_PIN_CONFIG_UNAVAILABLE = "EGE_PIN_CONFIG_UNAVAILABLE"
EGE_PIN_OBSERVED_UNAVAILABLE = "EGE_PIN_OBSERVED_UNAVAILABLE"

# EGE Rollback errors (Etapa 2.4)
EGE_ROLLBACK_NO_PINNED_RELEASE = "EGE_ROLLBACK_NO_PINNED_RELEASE"
EGE_ROLLBACK_PINNED_RELEASE_MISSING = "EGE_ROLLBACK_PINNED_RELEASE_MISSING"
EGE_ROLLBACK_SYMLINK_FAILED = "EGE_ROLLBACK_SYMLINK_FAILED"
EGE_ROLLBACK_BLOCKED_FROZEN = "EGE_ROLLBACK_BLOCKED_FROZEN"
EGE_ROLLBACK_BLOCKED_EMERGENCY = "EGE_ROLLBACK_BLOCKED_EMERGENCY"

# Runtime Reload errors (Etapa 6.6)
RUNTIME_RELOAD_FAILED = "RUNTIME_RELOAD_FAILED"
RUNTIME_RELOAD_BUNDLE_MISSING = "RUNTIME_RELOAD_BUNDLE_MISSING"
RUNTIME_OPERATION_NOT_FOUND = "RUNTIME_OPERATION_NOT_FOUND"

# Multi-tenant path misconfig errors (Etapa 2.6)
PATH_MISCONFIG_ABSOLUTE_LEDGER = "PATH_MISCONFIG_ABSOLUTE_LEDGER"
PATH_MISCONFIG_ABSOLUTE_STATE_STORE = "PATH_MISCONFIG_ABSOLUTE_STATE_STORE"

# Legacy Bridge errors (Etapa 2.7)
LEGACY_ASSET_NOT_FOUND = "LEGACY_ASSET_NOT_FOUND"
LEGACY_ASSET_ALREADY_EXISTS = "LEGACY_ASSET_ALREADY_EXISTS"
LEGACY_SOURCE_UNAVAILABLE = "LEGACY_SOURCE_UNAVAILABLE"
LEGACY_DRIFT_DETECTED = "LEGACY_DRIFT_DETECTED"
LEGACY_CONNECTOR_ERROR = "LEGACY_CONNECTOR_ERROR"
LEGACY_PATH_INVALID = "LEGACY_PATH_INVALID"

# Console session errors (Etapa 4.1)
CONSOLE_SESSION_SECRET_MISSING = "CONSOLE_SESSION_SECRET_MISSING"
CONSOLE_CSRF_INVALID = "CONSOLE_CSRF_INVALID"

# Governed Mandates errors (Etapa 2.8)
MANDATE_PROPOSAL_NOT_FOUND = "MANDATE_PROPOSAL_NOT_FOUND"
MANDATE_PROPOSAL_ALREADY_DECIDED = "MANDATE_PROPOSAL_ALREADY_DECIDED"
MANDATE_PROPOSAL_INVALID = "MANDATE_PROPOSAL_INVALID"
MANDATE_NOT_FOUND_FOR_UPDATE = "MANDATE_NOT_FOUND_FOR_UPDATE"
MANDATE_ALREADY_EXISTS = "MANDATE_ALREADY_EXISTS"
GOVERNED_MANDATES_UNAVAILABLE = "GOVERNED_MANDATES_UNAVAILABLE"

# Onboarding errors (Etapa 4.2)
TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND"
BUNDLE_GENERATION_FAILED = "BUNDLE_GENERATION_FAILED"
BUNDLE_COPY_FAILED = "BUNDLE_COPY_FAILED"
BUNDLE_ALREADY_EXISTS = "BUNDLE_ALREADY_EXISTS"
SEED_DSL_NOT_FOUND = "SEED_DSL_NOT_FOUND"
SEED_DSL_MISSING_FOR_DEPT = "SEED_DSL_MISSING_FOR_DEPT"

# Legacy Write errors (Etapa 4.3)
LEGACY_WRITE_ACTION_TYPE_UNKNOWN = "LEGACY_WRITE_ACTION_TYPE_UNKNOWN"
LEGACY_WRITE_PARAMS_INVALID = "LEGACY_WRITE_PARAMS_INVALID"
LEGACY_WRITE_DENIED_MANDATE = "LEGACY_WRITE_DENIED_MANDATE"
LEGACY_WRITE_DENIED_AUTONOMY = "LEGACY_WRITE_DENIED_AUTONOMY"
LEGACY_WRITE_DENIED_POLICY = "LEGACY_WRITE_DENIED_POLICY"
LEGACY_WRITE_OUTBOX_FAILED = "LEGACY_WRITE_OUTBOX_FAILED"
LEGACY_WRITE_ACTION_NOT_FOUND = "LEGACY_WRITE_ACTION_NOT_FOUND"

# Governed Policies errors (Etapa 4.4)
POLICY_PROPOSAL_NOT_FOUND = "POLICY_PROPOSAL_NOT_FOUND"
POLICY_PROPOSAL_ALREADY_DECIDED = "POLICY_PROPOSAL_ALREADY_DECIDED"
POLICY_PROPOSAL_INVALID = "POLICY_PROPOSAL_INVALID"
POLICY_NOT_FOUND_FOR_UPDATE = "POLICY_NOT_FOUND_FOR_UPDATE"
POLICY_ALREADY_EXISTS = "POLICY_ALREADY_EXISTS"
GOVERNED_POLICIES_UNAVAILABLE = "GOVERNED_POLICIES_UNAVAILABLE"

# Governed Autonomy errors (Etapa 4.4)
AUTONOMY_PROPOSAL_NOT_FOUND = "AUTONOMY_PROPOSAL_NOT_FOUND"
AUTONOMY_PROPOSAL_ALREADY_DECIDED = "AUTONOMY_PROPOSAL_ALREADY_DECIDED"
AUTONOMY_PROPOSAL_INVALID = "AUTONOMY_PROPOSAL_INVALID"
AUTONOMY_NOT_FOUND_FOR_UPDATE = "AUTONOMY_NOT_FOUND_FOR_UPDATE"
GOVERNED_AUTONOMY_UNAVAILABLE = "GOVERNED_AUTONOMY_UNAVAILABLE"

# Active Depts errors (Etapa 5.1)
DEPT_NOT_INSTALLED = "DEPT_NOT_INSTALLED"
DEPT_NOT_ACTIVE = "DEPT_NOT_ACTIVE"
DEPT_ALREADY_ACTIVE = "DEPT_ALREADY_ACTIVE"
DEPT_ALREADY_INACTIVE = "DEPT_ALREADY_INACTIVE"
CANNOT_DEACTIVATE_LAST_DEPT = "CANNOT_DEACTIVATE_LAST_DEPT"
ACTIVE_DEPTS_UNAVAILABLE = "ACTIVE_DEPTS_UNAVAILABLE"

# Actor Token errors (GAP 2 - Identity)
ACTOR_TOKEN_REQUIRED = "ACTOR_TOKEN_REQUIRED"
ACTOR_TOKEN_INVALID = "ACTOR_TOKEN_INVALID"
ACTOR_TOKEN_REVOKED = "ACTOR_TOKEN_REVOKED"
ACTOR_TOKEN_EXPIRED = "ACTOR_TOKEN_EXPIRED"
ACTOR_TOKEN_NOT_FOUND = "ACTOR_TOKEN_NOT_FOUND"
ACTOR_TOKENS_REGISTRY_UNAVAILABLE = "ACTOR_TOKENS_REGISTRY_UNAVAILABLE"
UNVERIFIED_IDENTITY_USED = "UNVERIFIED_IDENTITY_USED"

# Legacy Write Approval errors (GAP 3 - No Self-Approved)
LEGACY_WRITE_APPROVAL_REQUIRED = "LEGACY_WRITE_APPROVAL_REQUIRED"
LEGACY_WRITE_NO_APPROVAL_RULE_PROD = "LEGACY_WRITE_NO_APPROVAL_RULE_PROD"
LEGACY_WRITE_NO_ADMIN_ROLE_DEV = "LEGACY_WRITE_NO_ADMIN_ROLE_DEV"
LEGACY_WRITE_PENDING_APPROVAL = "LEGACY_WRITE_PENDING_APPROVAL"

# Agent Delegation errors (GAP 4 - Agents as Governed Actors)
ON_BEHALF_OF_NOT_AGENT = "ON_BEHALF_OF_NOT_AGENT"
ON_BEHALF_OF_INVALID = "ON_BEHALF_OF_INVALID"
AGENT_REQUEST_NOT_FOUND = "AGENT_REQUEST_NOT_FOUND"
AGENT_REQUESTS_REGISTRY_UNAVAILABLE = "AGENT_REQUESTS_REGISTRY_UNAVAILABLE"

# Preflight errors (GAP 5 - Secure Install Baseline)
PREFLIGHT_ADMIN_TOKEN_MISSING = "PREFLIGHT_ADMIN_TOKEN_MISSING"
PREFLIGHT_AUTH_MODE_INSECURE = "PREFLIGHT_AUTH_MODE_INSECURE"

# Institution secure config errors (GAP 5.3 - Non-silent prod)
INSTITUTION_SECURE_CONFIG_REQUIRED = "INSTITUTION_SECURE_CONFIG_REQUIRED"

# Migration check errors (Etapa 6.7)
MIGRATION_CHECK_FAILED = "MIGRATION_CHECK_FAILED"
MIGRATION_MISSING_OPERATIONS = "MIGRATION_MISSING_OPERATIONS"
MIGRATION_UNSUPPORTED_BIND_KIND = "MIGRATION_UNSUPPORTED_BIND_KIND"

# Workflow/Transition errors (Expansão 02)
WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
WORKFLOW_TRANSITION_NOT_FOUND = "WORKFLOW_TRANSITION_NOT_FOUND"
WORKFLOW_TRANSITION_CONFLICT = "WORKFLOW_TRANSITION_CONFLICT"
WORKFLOW_EFFECT_INVALID = "WORKFLOW_EFFECT_INVALID"
WORKFLOW_GUARD_UNSUPPORTED = "WORKFLOW_GUARD_UNSUPPORTED"

# Generic Approval errors (Expansão 03)
APPROVAL_NOT_FOUND = "APPROVAL_NOT_FOUND"
APPROVAL_ALREADY_DECIDED = "APPROVAL_ALREADY_DECIDED"
APPROVAL_FORBIDDEN = "APPROVAL_FORBIDDEN"
APPROVAL_SOD_VIOLATION = "APPROVAL_SOD_VIOLATION"
APPROVAL_INDEX_NOT_FOUND = "APPROVAL_INDEX_NOT_FOUND"
