openapi: 3.0.0
info:
  title: Sistema Checklist_Natural API
  version: 1.0.0
  description: API gerada automaticamente para Sistema Checklist_Natural
paths:
  /api/clientes:
    get:
      operationId: listCliente
      tags:
      - Cliente
      summary: Listar clientes
      responses:
        '200':
          description: Lista de clientes
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      operationId: createCliente
      tags:
      - Cliente
      summary: Criar cliente
      responses:
        '201':
          description: Cliente criado
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
  /api/clientes/{id}:
    get:
      operationId: getCliente
      tags:
      - Cliente
      summary: Obter cliente por ID
      responses:
        '200':
          description: Detalhes do cliente
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    put:
      operationId: updateCliente
      tags:
      - Cliente
      summary: Atualizar cliente
      responses:
        '200':
          description: Cliente atualizado
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
    delete:
      operationId: deleteCliente
      tags:
      - Cliente
      summary: Deletar cliente
      responses:
        '200':
          description: Cliente deletado
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
components:
  schemas:
    Cliente:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        email:
          type: string
      required:
      - id
      - nome
      - email
